# PowerShell script to compile, simulate Verilog code and open the VCD file in GTKWave


#fileName 
$fileName = "pfd"

# Paths to your Verilog files
$verilogFiles = @("tb_pfd.v")

# Output executable name
$outputVVP = "$fileName.vvp"

# VCD file generated by the simulation
$vcdFile = "$fileName.vcd"

#Iverilog Commands
& iverilog -o $outputVVP -i $verilogFiles
& vvp $outputVVP

#GTKWave Commands
& gtkwave $vcdFile
